// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DB_First_Using_EF_Core_Core_Power_Tools.Data.Context;
using DB_First_Using_EF_Core_Core_Power_Tools.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace DB_First_Using_EF_Core_Core_Power_Tools.Data.Context.Configurations
{
    public partial class CurrentProductListConfiguration : IEntityTypeConfiguration<CurrentProductList>
    {
        public void Configure(EntityTypeBuilder<CurrentProductList> entity)
        {
            entity
                .HasNoKey()
                .ToView("Current Product List");

            entity.Property(e => e.ProductId)
                .ValueGeneratedOnAdd()
                .HasColumnName("ProductID");
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(40);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CurrentProductList> entity);
    }
}
